#!/usr/bin/env ruby
require_relative '../lib/nd/shell_scripts'
include Nd::ShellScripts

if args?
  execute_and_record "git add #{args}"
else
  puts "git add . && git add -u"
  execute_and_record "git add . && git add -u"
end