#!/usr/bin/env ruby
require_relative '../lib/nd/shell_scripts'
include Nd::ShellScripts

if args?
  puts "bundle exec rake test TEST=#{args}"
  execute_and_record "bundle exec rake test TEST=#{args}"
else
  puts "bundle exec rake test:all"
  execute_and_record "bundle exec rake test:all"
end